"""baseline schema

本文件是**基线**：一次性建出 conversations / chat_messages / uploaded_documents /
feedback 四张表 + 索引 + 外键，也就是"从零建库"应有的样子。
由 autogenerate 对着一个**空库**生成 —— 对着已有数据的库 autogenerate 会得到空迁移，
起不到基线作用。

⚠️ 已经在用的库不要 `upgrade`，要先 `stamp`（否则表已存在会报错）：

    python -m alembic stamp head

这条只把版本号写进 alembic_version 表、不执行任何 DDL，正合"库已与 models 一致、
只是此前没版本管理"的既有部署。

历史上靠手写 SQL 做的迁移，语义已并入本基线，不再单独建 revision：
  · uploaded_documents.content_hash（CHAR(64) + 唯一索引 uq_uploads_content_hash）
  · feedback 的 UNIQUE(message_id) 与复合索引 idx_feedback_thumbs_time
旧脚本（scripts/migrate_feedback.py / migrate_clarification_flag.sql）留作历史记录，
新库不再需要执行。

已知差异（真库 vs 本基线）：本基线刻意保留真库的**历史实际状态** ——
`chat_messages.conversation_id` 为 nullable 且**无**外键。
原因是该表建库早于 `ForeignKey(...)` 声明，`create_all` 不会补结构，二者从未在真库生效。
由紧随其后的 `repair chat_messages` 一条 revision 收敛到 models 的最终形态
（清孤儿 → 收紧为 NOT NULL → 补 fk_chat_messages_conversation_id）。
为什么不直接把基线写成最终形态：那样真库被 stamp 在 head 后，缺失的外键永远不会被补上
（`upgrade` 认为无事可做），漂移会永久留在 `alembic check` 里。

Revision ID: e03c5380d2c8
Revises: 
Create Date: 2026-09-27 22:58:17.784078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03c5380d2c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件扩展名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='磁盘存储路径'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=True, comment='文件内容 SHA-256'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_documents')),
    sa.UniqueConstraint('content_hash', name='uq_uploads_content_hash')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=True, comment='所属会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sources', sa.Text(), nullable=True, comment='引用来源(JSON字符串)'),
    sa.Column('is_clarification', sa.Boolean(), nullable=False, comment='本条是否为证据不足的追问话术（阶段二）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='关联助手消息ID'),
    sa.Column('thumbs', sa.String(length=10), nullable=False, comment='评价: up/down'),
    sa.Column('corrected_answer', sa.Text(), nullable=True, comment='用户纠错文本(可选)'),
    sa.Column('comment', sa.String(length=500), nullable=True, comment='补充说明'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_feedback_message_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('message_id', name='uq_feedback_message_id')
    )
    op.create_index('idx_feedback_thumbs_time', 'feedback', ['thumbs', 'created_at'], unique=False)
    op.create_index(op.f('ix_feedback_message_id'), 'feedback', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ⚠️ 手工调整过：**不保留** autogenerate 生成的 `op.drop_index(...)`。
    # 原因（实测）：MySQL 报 1553 "Cannot drop index 'ix_chat_messages_conversation_id':
    # needed in a foreign key constraint" —— 外键还挂在这个索引上时不能单独删索引。
    # `drop_table` 本就会带走表上的全部索引，所以保持"先子表、后父表"的顺序即可：
    #   feedback → chat_messages（前者引用后者）→ uploaded_documents → conversations
    op.drop_table('feedback')
    op.drop_table('chat_messages')
    op.drop_table('uploaded_documents')
    op.drop_table('conversations')
